// <auto-generated />
using DoughnutBank.Entities.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoughnutBank.Migrations
{
    [DbContext(typeof(DoughnutBankContext))]
    partial class DoughnutBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DoughnutBank.Entities.OTP", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ExpirationTime")
                        .HasColumnType("bigint");

                    b.Property<string>("OTPValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserEmail");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("DoughnutBank.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OTPUserEmail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Email");

                    b.HasIndex("OTPUserEmail");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoughnutBank.Entities.User", b =>
                {
                    b.HasOne("DoughnutBank.Entities.OTP", "OTP")
                        .WithMany()
                        .HasForeignKey("OTPUserEmail");

                    b.Navigation("OTP");
                });
#pragma warning restore 612, 618
        }
    }
}
